# special_words.py
SPECIAL_WORDS = {
    # Mots interrogatifs
    "quel": "ki",
    "quelle": "ki",
    "quels": "ki",
    "quelles": "ki",
    "que": "ke",
    "qui" :"ki",
      
    # Articles indéfinis et partitifs
    "du vin": "diven",
    "de l'essence": "lésans",
    "de l'eau": "dlo",
    # Articles définis déjà intégrés - pas de -la
    "la nuit": "lannuit",
    "la mer": "lanmè",
    "la pluie": "lapli",
    # Articles définis agglutinatifs - conserver le -la
    "du vin": "diven",
    "l'église": "légliz-la",
    "l'orage": "lòraj-la", 
    "l'eau": "dlo-la",
    "l'argent": "lajan-la",
    "l'heure": "lè-la",
    "l'habitude": "labitid-la",
    "l'école": "lékòl-la",
    "l'année": "lanné-la",
    # Cas particuliers
    "au bord de la mer": "bòdlanmè",
    "grand bois": "granbwa",
    "petit enfant": "titimoun",
    "petit déjeuner": "tidéjené",
    "maçon": "mason",
    "un": "on",
    "une": "on",
    "chocolat": "chokola",
    "genou": "jounou",
    "syndicat": "sendika",
    "heureuse" : "érèz",
    "comme" : "kon",
    "prendre" : "pran",
    "grande" : "gran",
    "ville" : "vil",
    #Exception à la règle oi -wa
    "croire": "kwè",
    "voir": "vwè",
    "boire": "bwè",
    "avoir": "avwè",
    "revoir": "wouvwè",
    "recevoir": "risivwè",
    "froid": "fwèt",
    "soif": "swèf",
    "Boîte": "bwèt",
    "toile": "twèl",
    "soir": "swè",
    "moi": "mwen",
    "doigt": "dwèt",
    "vouloir" : "vlé",
    "rose" : "wòz",
    "roche" :"wòch",
    "noir" :"nwè",
    "rené" :"Réné",

   
}